[production]
address = "0.0.0.0"
port = 443
workers = 32
log = "critical"
limits = { forms = 32768 }
 
[development]
address = "0.0.0.0"
port = 3001
workers = 16
log = "normal"
limits = { forms = 32768 }
